# Generated by Django 2.0.4 on 2018-04-25 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theatre',
            name='tracking',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatres', to=settings.AUTH_USER_MODEL),
        ),
    ]
